FROM node:18
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
COPY prisma ./prisma/
##ignore husky
RUN npm install --ignore-scripts 
RUN npx prisma generate
COPY .env ./
EXPOSE 3456
CMD npm start