FROM node:18
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY swagger.json ./
COPY src ./src
COPY prisma ./prisma/
COPY .env ./
##ignore husky
RUN npm install --ignore-scripts 
RUN npx prisma generate
EXPOSE 3456
CMD npm start